server:
  port: 8080
spring:
  application:
    name: part1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.102.86.248:3306/shiermuzi_com?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: shiermuzi_com
    password: XHrbYCih8Z
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 1000MB
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml


logging:
  level:
    com:
      muzi: debug
